# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zIkJyFRqlPFeo-0c2VG-Q2lOw_Uc2xU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Coloque os arquivos das tabelas na pasta Content, por favor.")

# Caminhos dos arquivos CSV
caminho_arquivos = {
    "product": "/content/product.csv",
    "rideaddress_v1": "/content/rideaddress_v1.csv",
    "rideestimative_v3": "/content/rideestimative_v3.csv",
    "ride_v2": "/content/ride_v2.csv"
}

dataframes = {}

# Coleta dos Dados Iniciais
for nome, path in caminho_arquivos.items():
    dataframes[nome] = pd.read_csv(path, delimiter=";")
print("")
print("Funcionando")

# Descrição dos Dados
for nome, df in dataframes.items():
    print(f"\n### Primeiras 3 linhas do dataset {nome}:\n")
    print(df.head(3))

for nome, df in dataframes.items():
    print(f"\n### Estatísticas do datasett {nome}:\n")
    print(df.describe(include='all'))
    print("\nContagem dos valores únicos por coluna:\n")
    print(df.nunique())

# Exploração dos Dados:
ride_estimative_df = dataframes["rideestimative_v3"]

plt.figure(figsize=(10, 5))
ride_estimative_df["ProductID"].value_counts().plot(kind="bar")
plt.title("Produtos Mais Pedidos")
plt.xlabel("Produto")
plt.ylabel("Quantidade de Pedidos")
plt.xticks(rotation=45)
plt.show()

produtos_ordem = ride_estimative_df.groupby("ProductID")["WaitingTime"].mean().sort_values(ascending=False)
plt.figure(figsize=(10, 5))
plt.plot(produtos_ordem, marker='o', linestyle='-')
plt.title("Tempo de Espera por Produto")
plt.xlabel("Produto")
plt.ylabel("Tempo de Espera (em minutos)")
plt.xticks(rotation=45)
plt.show()

# Qualidade dos Dados
for nome, df in dataframes.items():
    print(f"\n### Qualidade dos Dados no dataset {nome}:\n")
    print("Valores ausentes por coluna:")
    print(df.isnull().sum())
    print("\nInformações duplicadas:")
    print(df.duplicated().sum())